// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package bootstrap

import (
	"context"
	"github.com/juan-lee/genesys/bootstrap/cluster"
	"github.com/juan-lee/genesys/bootstrap/network"
)

// Injectors from inject_fakes.go:

func InjectFakeSelfManaged(ctx context.Context) (*cluster.Bootstrapper, error) {
	vNetProvider := network.ProvideFakeVirtualNetwork()
	baseNetworkProvider := network.ProvideBaseNetwork(vNetProvider)
	bootstrapper := cluster.ProvideSelfManaged(baseNetworkProvider)
	return bootstrapper, nil
}
