// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package network

import (
	"context"
	"github.com/juan-lee/genesys/reconciler/cloud"
)

// Injectors from inject_fakes.go:

func InjectFakeReconciler(ctx context.Context, cloud2 *cloud.ProviderOptions) (Reconciler, error) {
	vNetReconciler := ProvideFakeVirtualNetwork(cloud2)
	loadBalancerReconciler := ProvideFakeLoadBalancer(cloud2)
	networkReconciler := ProvideReconciler(cloud2, vNetReconciler, loadBalancerReconciler)
	return networkReconciler, nil
}
