// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package network

import (
	"context"
)

// Injectors from inject_fakes.go:

func InjectFakeBaseNetwork(ctx context.Context) (BaseNetworkProvider, error) {
	vNetProvider := ProvideFakeVirtualNetwork()
	baseNetworkProvider := ProvideBaseNetwork(vNetProvider)
	return baseNetworkProvider, nil
}
