// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package reconcilers

import (
	"context"
	"github.com/juan-lee/genesys/reconcilers/cluster"
	"github.com/juan-lee/genesys/reconcilers/network"
)

// Injectors from inject_fakes.go:

func InjectFakeSelfManaged(ctx context.Context) (*cluster.Reconciler, error) {
	vNetProvider := network.ProvideFakeVirtualNetwork()
	baseNetworkProvider := network.ProvideBaseNetwork(vNetProvider)
	reconciler := cluster.ProvideSelfManaged(baseNetworkProvider)
	return reconciler, nil
}
